version: '3.4'

services:
  recipe-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    networks:
      - app
    ports:
      - 3000:3000
    command: [sh, -c, 'npm run start']
    volumes:
      - .:/app:delegated
      - /app/node_modules

networks:
  app:
