import { DispatcherDto, FreteRapidoRequestDto, RecipientDto, ShipperDto, VolumeDto } from "../dtos/freteRapido.dto";
import { QuoteModel, QuoteRequestDto } from "../dtos/quote.dto";

export function formatQuoteRequest(req: QuoteRequestDto){
    const shipper = new ShipperDto("25438296000158", "1d52a9b6b78cf07b08586152459a5c90", "5AKVkHqCn");

    const recipient = new RecipientDto(0, "", "", "BRA", Number(req.recipient.address.zipcode));

    const dispatchers = [formatDispatcher(req)];
    
    return new FreteRapidoRequestDto(
        shipper,
        recipient,
        dispatchers,
        [0,1]
    );
}

export function transformResToModel(offers: any[]): QuoteModel[] {
    if(!offers) return [];
    
    return offers.map((data) => new QuoteModel(data.final_price, data.carrier.name, data.service));
}

function formatDispatcher(req: QuoteRequestDto): DispatcherDto{
    const dispatcher = new DispatcherDto("25438296000158", 29161376, []);

    for(const vol of req.volumes){
        dispatcher.volumes.push(new VolumeDto(
            vol.amount,
            categories[vol.category],
            vol.height,
            vol.width,
            vol.length,
            vol.price,
            vol.unitary_weight,
        ));
    }

    return dispatcher;
}

const categories = {
    1: "Abrasivos",
    155: "Acessório infantil",
    109: "Acessório para decoração (com vidro)",
    110: "Acessório para decoração (sem vidro)",
    111: "Acessórios automotivos",
    69: "Acessórios de Airsoft / Paintball",
    73: "Acessórios de Arquearia",
    149: "Acessórios de montaria",
    70: "Acessórios de Pesca",
    112: "Acessórios para bicicleta",
    90: "Acessórios para celular",
    130: "Acessórios para Narguilés",
    132: "Acessórios para Tabacaria",
    2: "Adubos / Fertilizantes",
    74: "Alimentos não perecíveis",
    3: "Alimentos perecíveis",
    145: "Armações de óculos",
    72: "Arquearia",
    113: "Artesanatos (com vidro)",
    93: "Artesanatos (sem vidro)",
    152: "Artigos de festas",
    82: "Artigos para Camping",
    4: "Artigos para Pesca",
    5: "Auto Peças",
    133: "Banheira Acrílico",
    134: "Banheira de Aço Esmaltada",
    135: "Banheira Fibra de Vidro",
    156: "Banheira infantil",
    128: "Bebedouros e Purificadores",
    6: "Bebidas / Destilados",
    114: "Bicicletas (desmontada)",
    99: "Bijuteria",
    7: "Brindes",
    8: "Brinquedos",
    157: "Cadeirinha para automóvel",
    146: "Caixa d'água (Completa)",
    75: "Caixa de embalagem",
    136: "Caixa Plástica",
    9: "Calçados",
    115: "Cama / Mesa / Banho",
    62: "Cargas refrigeradas/congeladas",
    158: "Carrinho de bebê",
    137: "Cartucho de Gás",
    10: "CD / DVD / Blu-Ray",
    122: "Celulares e Smartphones",
    116: "Chapas de madeira",
    121: "Chip de celular",
    102: "Cocção Industrial",
    66: "Colchão",
    11: "Combustíveis / Óleos",
    12: "Confecção",
    13: "Cosméticos",
    14: "Couro",
    15: "Derivados Petróleo",
    16: "Descartáveis",
    17: "Editorial",
    19: "Eletrodomésticos",
    125: "Eletrodomésticos industriais",
    150: "Eletroportáteis",
    18: "Eletrônicos",
    20: "Embalagens",
    138: "Equipamento oftalmológico",
    107: "Equipamentos de cozinha industrial",
    88: "Equipamentos de Segurança / API",
    151: "Equipamentos para solda",
    84: "Estiletes / Materiais Cortantes",
    106: "Estufa térmica",
    21: "Explosivos / Pirotécnicos",
    126: "Expositor industrial",
    87: "Extintores",
    23: "Ferragens",
    24: "Ferramentas",
    25: "Fibras Ópticas",
    26: "Fonográfico",
    27: "Fotográfico",
    28: "Fraldas / Geriátricas",
    29: "Higiene",
    30: "Impressos",
    31: "Informática / Computadores",
    32: "Instrumento Musical",
    100: "Joia",
    144: "Lentes de contato",
    86: "Limpeza",
    77: "Linha Branca",
    33: "Livro(s)",
    79: "Malas / Mochilas",
    117: "Manequins",
    104: "Maquina de algodão doce",
    105: "Maquina de chocolate",
    34: "Materiais Escolares",
    35: "Materiais Esportivos",
    36: "Materiais Frágeis",
    97: "Materiais hidráulicos / Encanamentos",
    37: "Material de Construção",
    38: "Material de Irrigação",
    154: "Material de Jardinagem",
    141: "Material de laboratório",
    39: "Material Elétrico / Lâmpada(s)",
    40: "Material Gráfico",
    41: "Material Hospitalar",
    42: "Material Odontológico",
    139: "Material oftalmológico",
    43: "Material Pet Shop",
    50: "Material Plástico",
    44: "Material Veterinário",
    127: "Maçanetas",
    22: "Medicamentos",
    46: "Moto Peças",
    47: "Mudas / Plantas",
    80: "Máquina / Equipamentos",
    68: "Móveis com peças de vidro",
    64: "Móveis desmontados",
    159: "Móveis infantis",
    45: "Móveis montados",
    129: "Narguilés",
    999: "Outros",
    48: "Papelaria / Documentos",
    63: "Papelão",
    49: "Perfumaria",
    98: "Pia / Vasos",
    83: "Pilhas / Baterias",
    92: "Pisos (cerâmica) / Revestimentos",
    96: "Placa de Energia Solar",
    51: "Pneus e Borracharia",
    95: "Porta / Janelas (sem vidro)",
    118: "Portas / Janelas (com vidro)",
    124: "Portáteis industriais",
    85: "Produto Químico classificado",
    52: "Produtos Cerâmicos",
    143: "Produtos de SexShop",
    53: "Produtos Químicos Não Classificados",
    54: "Produtos Veterinários",
    94: "Quadros / Molduras",
    81: "Rações / Alimento para Animal",
    101: "Refrigeração Industrial",
    153: "Relógios",
    55: "Revistas",
    148: "Selas e Arreios de montaria",
    56: "Sementes",
    71: "Simulacro de Arma / Airsoft",
    65: "Sofá",
    57: "Suprimentos Agrícolas / Rurais",
    131: "Tabacaria",
    147: "Tampa de Caixa d'água",
    108: "Tapeçaria / Cortinas / Persianas",
    123: "Telefonia Fixa e Sem Fio",
    142: "Tinta",
    91: "Toldos",
    119: "Torneiras",
    67: "Travesseiro",
    76: "TV / Monitores",
    58: "Têxtil",
    103: "Utensílios industriais",
    89: "Utilidades domésticas",
    59: "Vacinas",
    120: "Vasos de polietileno",
    60: "Vestuário",
    61: "Vidros / Frágil",
    78: "Vitaminas / Suplementos nutricionais",
    140: "Óculos e acessórios"
};
  